### ISSUE TITLE
Show compiled model output

### ISSUE THREAD

**Issue by lewish** [tada-science/dataform-tracking#10]
Should have a way for users to see the compiled output of a model for debugging issues with macros etc.

**Comment by G2H** [comment]
We may need to have a way to compile an individual model/analysis/test in order to do that.
We also discussed having the full statements in the logs. The content of DBT run only shows the SQL, not the create table and so on. It is planned to be in DBT by the [end of August,](https://github.com/fishtown-analytics/dbt/issues/588), we may want to have a hack before that

**Comment by lewish** [comment]
Here's the hack: https://github.com/lewish/dbt/commit/8123a3f19ee951032d463347862e11939d908ea7

**Comment by G2H** [comment]
If the file exists in debug, show it, otherwise show the compiled and add a few comments at the top
